"""Create Character model

Revision ID: 4909bf282e33
Revises: 
Create Date: 2023-06-19 15:36:42.199876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4909bf282e33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('ingested', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('comics',
    sa.Column('comic_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('issue_number', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('comic_id')
    )
    op.create_table('powers',
    sa.Column('power_id', sa.String(), nullable=False),
    sa.Column('power_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('power_id')
    )
    op.create_table('character_comic_association',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('comic_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.comic_id'], ),
    sa.PrimaryKeyConstraint('character_id', 'comic_id')
    )
    op.create_table('character_power_association',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('power_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ),
    sa.ForeignKeyConstraint(['power_id'], ['powers.power_id'], ),
    sa.PrimaryKeyConstraint('character_id', 'power_id')
    )
    op.create_table('character_stats',
    sa.Column('character_stat_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('combat', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ),
    sa.PrimaryKeyConstraint('character_stat_id')
    )
    op.create_table('characters_wiki',
    sa.Column('character_wiki_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('skin_color', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('identity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('appearances', sa.Integer(), nullable=True),
    sa.Column('first_appearance', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('universe', sa.String(), nullable=True),
    sa.Column('character_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ),
    sa.PrimaryKeyConstraint('character_wiki_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters_wiki')
    op.drop_table('character_stats')
    op.drop_table('character_power_association')
    op.drop_table('character_comic_association')
    op.drop_table('powers')
    op.drop_table('comics')
    op.drop_table('characters')
    # ### end Alembic commands ###
