"""test

Revision ID: 5939ed38d35b
Revises: 4909bf282e33
Create Date: 2023-06-19 18:44:36.896388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5939ed38d35b'
down_revision = '4909bf282e33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
